r"""Fused Triton GBM path generator with a hand-written adjoint.

Why this kernel exists
======================
The pure-PyTorch simulator in :mod:`src.models.gbm` is correct and fully
differentiable, but it is **global-memory-bandwidth bound**. A single call to
``simulate_gbm`` materialises roughly five :math:`M \times N` tensors in HBM:

===========================  ==============================================
tensor                       produced by
===========================  ==============================================
``sigma * dW``               elementwise multiply
``drift + sigma * dW``       elementwise add
``cumsum(...)``              scan
``cat(zeros, ...)``          concatenation to width :math:`N+1`
``s0 * exp(...)``            exponential + scale
===========================  ==============================================

Every one of those is a full round trip to device memory for what is
arithmetically a handful of FLOPs per element. The kernel below performs the
entire chain -- increment scaling, the running cumulative sum along time, the
exponential, and the :math:`S_0` scale -- inside registers and SRAM, reading
``dW`` **once** and writing the path matrix **once**.

The scan strategy
=================
The cumulative sum runs along *time*, while paths are mutually independent. So
each Triton program owns a tile of ``BLOCK_M`` paths and walks the whole time
axis itself, carrying a running offset between chunks of ``BLOCK_N`` steps:

.. code-block:: text

    carry = 0
    for each chunk of BLOCK_N time steps:
        incr      = drift + sigma * dW[chunk]          # in registers
        log_path  = cumsum(incr, axis=time) + carry    # in SRAM
        S[chunk]  = s0 * exp(log_path)                 # single store
        carry    += sum(incr, axis=time)

Chunking (rather than one giant ``BLOCK_N >= N`` tile) keeps SRAM pressure
bounded and makes the kernel work for any :math:`N`, not just small ones.

The adjoint -- derived, not autogenerated
=========================================
Triton kernels are opaque to PyTorch's autograd, so the backward pass must be
written by hand. Getting it exactly right is non-negotiable: the whole Phase 1-2
pipeline (Greeks, CVA sensitivities) hangs off these gradients.

With :math:`a = (\mu - \tfrac12\sigma^2)\Delta t` and
:math:`\iota_{m,j} = a + \sigma\,\Delta W_{m,j}`, the forward map is

.. math::
    L_{m,k} = \sum_{j=1}^{k} \iota_{m,j},
    \qquad S_{m,k} = S_0 e^{L_{m,k}},
    \qquad S_{m,0} = S_0 .

Let :math:`G_{m,k} = \partial\mathcal{L}/\partial S_{m,k}` be the incoming
adjoint. Then

.. math::
    \frac{\partial \mathcal{L}}{\partial L_{m,k}}
        = G_{m,k}\, S_0 e^{L_{m,k}} = G_{m,k} S_{m,k} \;=:\; P_{m,k},

and because :math:`L_{m,k}` accumulates *every* increment up to :math:`k`, the
adjoint of a single increment is a **suffix sum** of :math:`P`:

.. math::
    Q_{m,j} \;=\; \frac{\partial\mathcal{L}}{\partial \iota_{m,j}}
        \;=\; \sum_{k \ge j} P_{m,k}.

The three parameter gradients then follow by the chain rule through
:math:`\iota`:

.. math::
    \frac{\partial\mathcal{L}}{\partial S_0}
        &= \sum_{m,k} G_{m,k}\, e^{L_{m,k}}
         = \sum_m G_{m,0} + \frac{1}{S_0}\sum_{m,k\ge1} P_{m,k}, \\
    \frac{\partial\mathcal{L}}{\partial \mu}
        &= \Delta t \sum_{m,j} Q_{m,j}, \\
    \frac{\partial\mathcal{L}}{\partial \sigma}
        &= \sum_{m,j} Q_{m,j}\left(\Delta W_{m,j} - \sigma\,\Delta t\right), \\
    \frac{\partial\mathcal{L}}{\partial \Delta W_{m,j}}
        &= \sigma\, Q_{m,j}.

The :math:`-\sigma\Delta t` term in the Vega is the Ito correction's
contribution and is the single easiest thing to drop by accident; omitting it
produces a Vega that looks plausible and is wrong by
:math:`\sigma\Delta t\sum Q`.

Computing the suffix sum without a reverse scan
-----------------------------------------------
Rather than flipping tensors (which not every Triton version exposes), the
backward walks chunks **from the last to the first** and uses the identity

.. math::
    \underbrace{\sum_{i=j}^{hi-1} P_i}_{\text{suffix within chunk}}
    = \underbrace{\sum_{i=lo}^{hi-1} P_i}_{\text{chunk total}}
    - \underbrace{\sum_{i=lo}^{j} P_i}_{\text{inclusive prefix}}
    + P_j ,

so only forward ``cumsum`` and ``sum`` primitives are needed.

Determinism
-----------
The scalar gradients are reduced via **per-program partial buffers summed in
PyTorch**, not ``tl.atomic_add``. Atomics would make the result depend on
program completion order, so two identical runs could differ in the last bits --
unacceptable for a thesis benchmark, and a nightmare to debug against a
finite-difference oracle. The partial-buffer reduction is bitwise reproducible
and sidesteps the patchy float64 atomic support in Triton.

Known limitation: no double backward
====================================
:meth:`FusedGBMFunction.backward` is marked ``once_differentiable``. The kernel
path therefore supports first-order sensitivities only -- attempting to
differentiate the gradient (for Gamma, or a Hessian-vector product) raises a
clear error rather than returning silent garbage. The pure-PyTorch path in
:mod:`src.models.gbm` *does* support double backward, and
:func:`reference_gbm_backward` below is itself written in differentiable
PyTorch, so second-order work has a validated fallback. Making the Triton
adjoint itself differentiable would mean writing a second-order kernel; that is
deliberately out of Phase 3 scope.

Future work
-----------
``dW`` is still materialised in HBM by the caller. Folding a counter-based
(Philox) RNG into the kernel would remove that :math:`M \times N` allocation
entirely and make peak memory :math:`O(M)` rather than :math:`O(MN)`. That is
the natural next optimisation once this kernel is validated.
"""

# NOTE: `from __future__ import annotations` is deliberately NOT used in this
# module. Triton inspects `tl.constexpr` annotations as live objects to decide
# which parameters are compile-time constants; postponed (string) annotations
# would silently demote them to runtime arguments and break compilation.

import math
from typing import Optional, Tuple

import torch
from torch import Tensor

__all__ = [
    "HAS_TRITON",
    "is_available",
    "FusedGBMFunction",
    "triton_simulate_gbm",
    "reference_gbm_backward",
    "select_block_sizes",
]


# --------------------------------------------------------------------------
# Guarded import.
#
# This project's CPU test suite must keep working on machines without Triton
# (notably Windows, where Triton has no official wheel). The stubs below let the
# module import cleanly; any attempt to actually *use* the kernels raises a
# clear, actionable error instead of an ImportError at collection time.
# --------------------------------------------------------------------------
try:  # pragma: no cover - exercised only where Triton is installed
    import triton
    import triton.language as tl

    HAS_TRITON = True
except ImportError:  # pragma: no cover - exercised only where Triton is absent

    class _TritonStub:
        """Minimal stand-in so ``@triton.jit`` decorated defs still parse."""

        @staticmethod
        def jit(function):
            return function

        @staticmethod
        def cdiv(numerator, denominator):
            return -(-numerator // denominator)

        def __getattr__(self, name):
            raise RuntimeError(
                f"Triton is not installed; triton.{name} is unavailable. "
                "Install Triton on a CUDA machine to use the fused kernels."
            )

    class _TritonLanguageStub:
        """Stub exposing ``constexpr`` so annotations evaluate at import time."""

        def __init__(self):
            # Must be a real attribute: it is evaluated when the kernel
            # functions below are defined.
            self.constexpr = object()
            self.float32 = object()
            self.float64 = object()

        def __getattr__(self, name):
            raise RuntimeError(
                f"Triton is not installed; tl.{name} is unavailable. "
                "Install Triton on a CUDA machine to use the fused kernels."
            )

    triton = _TritonStub()
    tl = _TritonLanguageStub()
    HAS_TRITON = False


def is_available() -> bool:
    """Report whether the fused kernels can actually run here.

    Returns:
        ``True`` only when Triton is importable *and* a CUDA device is visible.
    """
    return HAS_TRITON and torch.cuda.is_available()


def _require_runtime() -> None:
    """Raise a precise error when the fused path cannot run.

    Raises:
        RuntimeError: If Triton is missing or no CUDA device is present.
    """
    if not HAS_TRITON:
        raise RuntimeError(
            "Triton is not installed. The fused GBM kernel requires Triton and a "
            "CUDA device; use src.models.gbm.simulate_gbm for the portable path."
        )
    if not torch.cuda.is_available():
        raise RuntimeError(
            "No CUDA device is visible to PyTorch. The fused GBM kernel is "
            "GPU-only; use src.models.gbm.simulate_gbm on CPU."
        )


# ==========================================================================
# Block-size selection
# ==========================================================================
def select_block_sizes(n_steps: int, element_size: int) -> Tuple[int, int]:
    """Choose ``(BLOCK_M, BLOCK_N)`` for a given time-axis length and dtype.

    ``BLOCK_N`` is the time-chunk width and must be a power of two because
    Triton's ``cumsum`` operates on power-of-two tiles. ``BLOCK_M`` is then
    chosen so the working tile stays inside a modest SRAM budget, leaving room
    for several concurrent programs per streaming multiprocessor.

    Args:
        n_steps: Number of time steps :math:`N`.
        element_size: Bytes per element (``4`` for float32, ``8`` for float64).

    Returns:
        ``(BLOCK_M, BLOCK_N)``, both powers of two.

    Raises:
        ValueError: If ``n_steps`` or ``element_size`` is non-positive.
    """
    if n_steps <= 0:
        raise ValueError(f"n_steps must be positive, got {n_steps}")
    if element_size <= 0:
        raise ValueError(f"element_size must be positive, got {element_size}")

    # Next power of two at or above n_steps, capped so a long horizon is walked
    # in several chunks rather than one oversized tile.
    block_n = 1 << max(0, (n_steps - 1).bit_length())
    block_n = max(16, min(block_n, 128))

    # ~32 KiB per tile keeps occupancy healthy on every CUDA architecture we
    # care about, without querying device properties at import time.
    tile_budget_bytes = 32 * 1024
    block_m = tile_budget_bytes // (block_n * element_size)
    block_m = max(1, min(64, block_m))
    block_m = 1 << (block_m.bit_length() - 1)  # round down to a power of two

    return block_m, block_n


# ==========================================================================
# Kernels
# ==========================================================================
@triton.jit
def _fused_gbm_forward_kernel(
    dw_ptr,
    params_ptr,
    out_ptr,
    n_paths,
    n_steps,
    dw_stride_m,
    dw_stride_n,
    out_stride_m,
    out_stride_n,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    DTYPE: tl.constexpr,
):
    """Fuse increment scaling, the time-axis scan, ``exp`` and the S0 scale.

    Each program owns ``BLOCK_M`` paths and walks the entire time axis in
    chunks of ``BLOCK_N``, carrying the running log-path offset between chunks.

    Args:
        dw_ptr: Brownian increments, shape ``(n_paths, n_steps)``.
        params_ptr: Packed ``[s0, mu, sigma, dt]`` in the working dtype. Passed
            as a device tensor rather than as Python floats so that float64
            precision survives -- scalar JIT arguments would be demoted to
            float32.
        out_ptr: Output paths, shape ``(n_paths, n_steps + 1)``.
        n_paths: Number of paths :math:`M`.
        n_steps: Number of time steps :math:`N`.
        dw_stride_m: Row stride of ``dw_ptr``.
        dw_stride_n: Column stride of ``dw_ptr``.
        out_stride_m: Row stride of ``out_ptr``.
        out_stride_n: Column stride of ``out_ptr``.
        BLOCK_M: Paths per program.
        BLOCK_N: Time steps per chunk (power of two).
        DTYPE: Working element type.
    """
    pid = tl.program_id(axis=0)
    offs_m = pid * BLOCK_M + tl.arange(0, BLOCK_M)
    mask_m = offs_m < n_paths

    s0 = tl.load(params_ptr + 0)
    mu = tl.load(params_ptr + 1)
    sigma = tl.load(params_ptr + 2)
    dt = tl.load(params_ptr + 3)

    # Ito-corrected drift per step.
    drift = (mu - 0.5 * sigma * sigma) * dt

    zeros_m = tl.zeros([BLOCK_M], dtype=DTYPE)
    zeros_mn = tl.zeros([BLOCK_M, BLOCK_N], dtype=DTYPE)

    # Column 0 is exactly S0 on every path (log-path offset zero).
    tl.store(out_ptr + offs_m * out_stride_m, s0 + zeros_m, mask=mask_m)

    carry = zeros_m
    for start in range(0, n_steps, BLOCK_N):
        offs_n = start + tl.arange(0, BLOCK_N)
        mask_n = offs_n < n_steps
        mask = mask_m[:, None] & mask_n[None, :]

        dw = tl.load(
            dw_ptr + offs_m[:, None] * dw_stride_m + offs_n[None, :] * dw_stride_n,
            mask=mask,
            other=0.0,
        )
        # The `where` is essential: padded lanes must contribute zero, but
        # `drift + sigma * 0` is `drift`, which would leak spurious drift into
        # both the scan and the carry.
        increments = tl.where(mask, drift + sigma * dw, zeros_mn)

        log_path = tl.cumsum(increments, axis=1) + carry[:, None]

        # Time index j lands in output column j + 1.
        tl.store(
            out_ptr
            + offs_m[:, None] * out_stride_m
            + (offs_n[None, :] + 1) * out_stride_n,
            s0 * tl.exp(log_path),
            mask=mask,
        )

        carry = carry + tl.sum(increments, axis=1)


@triton.jit
def _fused_gbm_backward_kernel(
    grad_out_ptr,
    out_ptr,
    dw_ptr,
    params_ptr,
    grad_dw_ptr,
    partial_s0_ptr,
    partial_mu_ptr,
    partial_sigma_ptr,
    n_paths,
    n_steps,
    go_stride_m,
    go_stride_n,
    out_stride_m,
    out_stride_n,
    dw_stride_m,
    dw_stride_n,
    gdw_stride_m,
    gdw_stride_n,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    DTYPE: tl.constexpr,
):
    """Hand-written adjoint of :func:`_fused_gbm_forward_kernel`.

    Walks time chunks in **reverse** to accumulate the suffix sum
    :math:`Q_{m,j} = \\sum_{k\\ge j} G_{m,k}S_{m,k}`, then contracts it against
    :math:`\\partial\\iota/\\partial\\theta` for each parameter. Scalar
    gradients are written as per-program partials and reduced host-side, which
    keeps the result bitwise reproducible.

    Args:
        grad_out_ptr: Incoming adjoint, shape ``(n_paths, n_steps + 1)``.
        out_ptr: Forward output :math:`S`, shape ``(n_paths, n_steps + 1)``.
        dw_ptr: Brownian increments, shape ``(n_paths, n_steps)``.
        params_ptr: Packed ``[s0, mu, sigma, dt]``.
        grad_dw_ptr: Output gradient w.r.t. ``dW``, shape ``(n_paths, n_steps)``.
        partial_s0_ptr: Per-program partial sums for ``dL/ds0``.
        partial_mu_ptr: Per-program partial sums for ``dL/dmu``.
        partial_sigma_ptr: Per-program partial sums for ``dL/dsigma``.
        n_paths: Number of paths :math:`M`.
        n_steps: Number of time steps :math:`N`.
        go_stride_m: Row stride of ``grad_out_ptr``.
        go_stride_n: Column stride of ``grad_out_ptr``.
        out_stride_m: Row stride of ``out_ptr``.
        out_stride_n: Column stride of ``out_ptr``.
        dw_stride_m: Row stride of ``dw_ptr``.
        dw_stride_n: Column stride of ``dw_ptr``.
        gdw_stride_m: Row stride of ``grad_dw_ptr``.
        gdw_stride_n: Column stride of ``grad_dw_ptr``.
        BLOCK_M: Paths per program.
        BLOCK_N: Time steps per chunk (power of two).
        DTYPE: Working element type.
    """
    pid = tl.program_id(axis=0)
    offs_m = pid * BLOCK_M + tl.arange(0, BLOCK_M)
    mask_m = offs_m < n_paths

    s0 = tl.load(params_ptr + 0)
    sigma = tl.load(params_ptr + 2)
    dt = tl.load(params_ptr + 3)

    zeros_m = tl.zeros([BLOCK_M], dtype=DTYPE)
    zeros_mn = tl.zeros([BLOCK_M, BLOCK_N], dtype=DTYPE)

    # Column 0 depends on S0 directly (dS/dS0 = 1) and on nothing else.
    grad_column_zero = tl.load(
        grad_out_ptr + offs_m * go_stride_m, mask=mask_m, other=0.0
    )
    acc_s0 = tl.where(mask_m, grad_column_zero, zeros_m)
    acc_mu = zeros_m
    acc_sigma = zeros_m

    # `carry` holds the suffix sum of P over every time index beyond the chunk
    # currently being processed.
    carry = zeros_m
    n_chunks = (n_steps + BLOCK_N - 1) // BLOCK_N

    for chunk in range(0, n_chunks):
        # Reverse traversal expressed with a forward loop: Triton's support for
        # negative-step ranges over runtime bounds is version-dependent.
        start = (n_chunks - 1 - chunk) * BLOCK_N
        offs_n = start + tl.arange(0, BLOCK_N)
        mask_n = offs_n < n_steps
        mask = mask_m[:, None] & mask_n[None, :]

        column_offsets = (offs_n[None, :] + 1) * go_stride_n
        grad_slice = tl.load(
            grad_out_ptr + offs_m[:, None] * go_stride_m + column_offsets,
            mask=mask,
            other=0.0,
        )
        path_slice = tl.load(
            out_ptr
            + offs_m[:, None] * out_stride_m
            + (offs_n[None, :] + 1) * out_stride_n,
            mask=mask,
            other=0.0,
        )

        # P = dL/dlog_path = G * S.
        p = tl.where(mask, grad_slice * path_slice, zeros_mn)
        chunk_total = tl.sum(p, axis=1)

        # Suffix sum inside the chunk, built from forward primitives:
        #     suffix[j] = total - inclusive_prefix[j] + P[j]
        suffix = chunk_total[:, None] - tl.cumsum(p, axis=1) + p
        q = tl.where(mask, suffix + carry[:, None], zeros_mn)

        tl.store(
            grad_dw_ptr
            + offs_m[:, None] * gdw_stride_m
            + offs_n[None, :] * gdw_stride_n,
            sigma * q,
            mask=mask,
        )

        dw = tl.load(
            dw_ptr + offs_m[:, None] * dw_stride_m + offs_n[None, :] * dw_stride_n,
            mask=mask,
            other=0.0,
        )

        acc_s0 = acc_s0 + chunk_total / s0
        acc_mu = acc_mu + tl.sum(q, axis=1) * dt
        acc_sigma = acc_sigma + tl.sum(q * (dw - sigma * dt), axis=1)
        carry = carry + chunk_total

    tl.store(partial_s0_ptr + pid, tl.sum(acc_s0, axis=0))
    tl.store(partial_mu_ptr + pid, tl.sum(acc_mu, axis=0))
    tl.store(partial_sigma_ptr + pid, tl.sum(acc_sigma, axis=0))


# ==========================================================================
# Pure-PyTorch reference adjoint (CPU-testable)
# ==========================================================================
def reference_gbm_backward(
    grad_out: Tensor,
    paths: Tensor,
    dW: Tensor,
    s0: Tensor,
    sigma: Tensor,
    dt: float,
) -> Tuple[Tensor, Tensor, Tensor, Tensor]:
    r"""Vectorised PyTorch implementation of the same analytic adjoint.

    This exists so the *mathematics* of the backward pass can be validated
    against ``torch.autograd`` on a CPU-only machine, independently of whether
    Triton or a GPU is available. The Triton kernel implements exactly these
    formulas; if this function agrees with autograd and the kernel agrees with
    this function, the kernel is correct.

    It is also written in ordinary differentiable PyTorch, so unlike the kernel
    it supports double backward -- making it the fallback for second-order work
    (Gamma, Hessian-vector products).

    Args:
        grad_out: Incoming adjoint :math:`G`, shape ``(n_paths, n_steps + 1)``.
        paths: Forward output :math:`S`, shape ``(n_paths, n_steps + 1)``.
        dW: Brownian increments, shape ``(n_paths, n_steps)``.
        s0: Initial spot, 0-dim tensor. Must be non-zero.
        sigma: Volatility, 0-dim tensor.
        dt: Time step.

    Returns:
        ``(grad_s0, grad_mu, grad_sigma, grad_dW)``. The three parameter
        gradients are 0-dim; ``grad_dW`` matches ``dW``'s shape.

    Raises:
        ValueError: On inconsistent shapes.
    """
    if grad_out.shape != paths.shape:
        raise ValueError(
            f"grad_out {tuple(grad_out.shape)} must match paths {tuple(paths.shape)}"
        )
    if dW.shape[0] != paths.shape[0] or dW.shape[1] != paths.shape[1] - 1:
        raise ValueError(
            f"dW {tuple(dW.shape)} inconsistent with paths {tuple(paths.shape)}"
        )

    # P[:, j] is the adjoint of log_path at time index j (output column j + 1).
    p = grad_out[:, 1:] * paths[:, 1:]

    # Q is the suffix sum of P along time: Q[:, j] = sum_{i >= j} P[:, i].
    # Implemented as flip -> cumsum -> flip, which is the readable form; the
    # kernel uses the total-minus-prefix identity instead to avoid needing a
    # reverse scan primitive.
    q = torch.flip(torch.cumsum(torch.flip(p, dims=(1,)), dim=1), dims=(1,))

    grad_dw = sigma * q
    grad_mu = q.sum() * dt
    # The -sigma*dt term is the Ito correction's contribution to Vega.
    grad_sigma = (q * (dW - sigma * dt)).sum()
    grad_s0 = grad_out[:, 0].sum() + p.sum() / s0

    return grad_s0, grad_mu, grad_sigma, grad_dw


# ==========================================================================
# autograd.Function
# ==========================================================================
class FusedGBMFunction(torch.autograd.Function):
    """Autograd wrapper binding the fused kernels into the existing AAD pipeline.

    The forward pass runs :func:`_fused_gbm_forward_kernel`; the backward pass
    runs :func:`_fused_gbm_backward_kernel` and reduces its per-program partials
    host-side. From PyTorch's perspective this is an ordinary differentiable op,
    so everything downstream -- payoffs, exposure profiles, CVA, the Phase 1-2
    Greeks machinery -- keeps working unchanged.
    """

    @staticmethod
    def forward(  # type: ignore[override]
        ctx,
        s0: Tensor,
        mu: Tensor,
        sigma: Tensor,
        dW: Tensor,
        dt: float,
    ) -> Tensor:
        """Generate paths on the GPU.

        Args:
            ctx: Autograd context.
            s0: Initial spot, 0-dim tensor on the same device/dtype as ``dW``.
            mu: Drift, 0-dim tensor.
            sigma: Volatility, 0-dim tensor.
            dW: Brownian increments of shape ``(n_paths, n_steps)`` on CUDA.
            dt: Time step.

        Returns:
            Paths of shape ``(n_paths, n_steps + 1)``.
        """
        _require_runtime()

        n_paths, n_steps = dW.shape
        out = torch.empty(
            (n_paths, n_steps + 1), device=dW.device, dtype=dW.dtype
        )

        # Pack the scalars into a device tensor. Building it with torch.stack
        # (rather than float(...)) keeps everything on-device: reading a CUDA
        # scalar into Python would force a host sync on every call, which would
        # show up directly in the Phase 3 benchmark.
        params = torch.stack(
            (
                s0.reshape(()),
                mu.reshape(()),
                sigma.reshape(()),
                torch.as_tensor(dt, device=dW.device, dtype=dW.dtype),
            )
        ).contiguous()

        block_m, block_n = select_block_sizes(n_steps, dW.element_size())
        dtype = tl.float64 if dW.dtype == torch.float64 else tl.float32
        grid = (triton.cdiv(n_paths, block_m),)

        _fused_gbm_forward_kernel[grid](
            dW,
            params,
            out,
            n_paths,
            n_steps,
            dW.stride(0),
            dW.stride(1),
            out.stride(0),
            out.stride(1),
            BLOCK_M=block_m,
            BLOCK_N=block_n,
            DTYPE=dtype,
        )

        ctx.save_for_backward(dW, out, params)
        ctx.dt = dt
        ctx.block_m = block_m
        ctx.block_n = block_n
        return out

    @staticmethod
    @torch.autograd.function.once_differentiable
    def backward(  # type: ignore[override]
        ctx, grad_out: Tensor
    ) -> Tuple[Optional[Tensor], Optional[Tensor], Optional[Tensor], Optional[Tensor], None]:
        """Run the hand-written adjoint kernel.

        Args:
            ctx: Autograd context carrying the saved forward tensors.
            grad_out: Incoming adjoint of shape ``(n_paths, n_steps + 1)``.

        Returns:
            Gradients for ``(s0, mu, sigma, dW, dt)``; ``dt`` is a
            non-differentiable Python float so its slot is ``None``, and any
            input that did not require grad also yields ``None``.
        """
        dW, out, params = ctx.saved_tensors
        n_paths, n_steps = dW.shape

        # A non-contiguous incoming adjoint would still be handled by the
        # stride arguments, but making it contiguous keeps the loads coalesced.
        grad_out = grad_out.contiguous()

        grad_dw = torch.empty_like(dW)
        block_m, block_n = ctx.block_m, ctx.block_n
        n_programs = triton.cdiv(n_paths, block_m)

        partial_s0 = torch.empty(n_programs, device=dW.device, dtype=dW.dtype)
        partial_mu = torch.empty(n_programs, device=dW.device, dtype=dW.dtype)
        partial_sigma = torch.empty(n_programs, device=dW.device, dtype=dW.dtype)

        dtype = tl.float64 if dW.dtype == torch.float64 else tl.float32

        _fused_gbm_backward_kernel[(n_programs,)](
            grad_out,
            out,
            dW,
            params,
            grad_dw,
            partial_s0,
            partial_mu,
            partial_sigma,
            n_paths,
            n_steps,
            grad_out.stride(0),
            grad_out.stride(1),
            out.stride(0),
            out.stride(1),
            dW.stride(0),
            dW.stride(1),
            grad_dw.stride(0),
            grad_dw.stride(1),
            BLOCK_M=block_m,
            BLOCK_N=block_n,
            DTYPE=dtype,
        )

        needs_s0, needs_mu, needs_sigma, needs_dw, _ = ctx.needs_input_grad
        return (
            partial_s0.sum() if needs_s0 else None,
            partial_mu.sum() if needs_mu else None,
            partial_sigma.sum() if needs_sigma else None,
            grad_dw if needs_dw else None,
            None,
        )


# ==========================================================================
# User-facing helper
# ==========================================================================
def _as_param(value, device: torch.device, dtype: torch.dtype, name: str) -> Tensor:
    """Coerce a scalar-like parameter to a 0-dim tensor, preserving grad.

    Mirrors ``src.models.gbm._as_param`` so the two simulators accept exactly
    the same inputs.

    Args:
        value: Python float or scalar tensor.
        device: Target device.
        dtype: Target dtype.
        name: Parameter name for error messages.

    Returns:
        A 0-dim tensor on ``device`` with dtype ``dtype``.

    Raises:
        ValueError: If ``value`` is a tensor with more than one element.
    """
    if isinstance(value, Tensor):
        if value.numel() != 1:
            raise ValueError(
                f"model parameter {name!r} must be scalar, got shape {tuple(value.shape)}"
            )
        tensor = value.to(device=device, dtype=dtype)
        return tensor if tensor.ndim == 0 else tensor.reshape(())
    return torch.as_tensor(float(value), device=device, dtype=dtype)


def triton_simulate_gbm(s0, mu, sigma, dW: Tensor, dt: float) -> Tensor:
    r"""Fused GPU GBM simulation, API-compatible with :func:`src.models.gbm.simulate_gbm`.

    Drop-in replacement: identical signature, identical output shape and
    semantics, identical gradient behaviour. The only differences are that
    ``dW`` must live on a CUDA device and that second-order differentiation is
    unsupported (see the module docstring).

    Args:
        s0: Initial spot :math:`S_0`. Pass a tensor with ``requires_grad=True``
            to obtain Delta.
        mu: Drift :math:`\mu`. Equal to the risk-free rate under
            :math:`\mathbb{Q}`.
        sigma: Volatility :math:`\sigma`. Pass a tensor with
            ``requires_grad=True`` to obtain Vega.
        dW: Brownian increments of shape ``(n_paths, n_steps)`` on CUDA. Its
            device and dtype define those of the output.
        dt: Step size :math:`\Delta t` used to generate ``dW``.

    Returns:
        Paths of shape ``(n_paths, n_steps + 1)``. Column ``0`` is
        :math:`S_0` on every path; column ``k`` is :math:`S_{k\Delta t}`.

    Raises:
        RuntimeError: If Triton or CUDA is unavailable.
        ValueError: If ``dW`` is not a 2-D CUDA tensor, is empty, or ``dt`` is
            non-positive.

    Example:
        >>> dW = torch.randn(1024, 252, device="cuda", dtype=torch.float32)
        >>> s0 = torch.tensor(100.0, device="cuda", requires_grad=True)
        >>> paths = triton_simulate_gbm(s0, 0.03, 0.2, dW, 1.0 / 252)
        >>> paths.shape
        torch.Size([1024, 253])
    """
    _require_runtime()

    if not isinstance(dW, Tensor):
        raise ValueError(f"dW must be a torch.Tensor, got {type(dW).__name__}")
    if dW.ndim != 2:
        raise ValueError(
            f"dW must be 2-dimensional (n_paths, n_steps), got {tuple(dW.shape)}"
        )
    if dW.numel() == 0:
        raise ValueError("dW must be non-empty")
    if not dW.is_cuda:
        raise ValueError(
            "the fused kernel is GPU-only; dW must be a CUDA tensor "
            "(use src.models.gbm.simulate_gbm for CPU)"
        )
    if dW.dtype not in (torch.float32, torch.float64):
        raise ValueError(
            f"dW must be float32 or float64, got {dW.dtype}"
        )
    if not isinstance(dt, (int, float)) or isinstance(dt, bool):
        raise ValueError(f"dt must be a real number, got {type(dt).__name__}")
    if not math.isfinite(float(dt)) or float(dt) <= 0.0:
        raise ValueError(f"dt must be positive and finite, got {dt}")

    device, dtype = dW.device, dW.dtype
    s0_t = _as_param(s0, device, dtype, "s0")
    mu_t = _as_param(mu, device, dtype, "mu")
    sigma_t = _as_param(sigma, device, dtype, "sigma")

    return FusedGBMFunction.apply(s0_t, mu_t, sigma_t, dW, float(dt))
